<a href="https://colab.research.google.com/github/NewtonSawitta/BasicProg_DataViz65/blob/main/Recap_4_5_Quiz2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# Matrix Slicing

In [17]:
import numpy 

In [18]:
mat_a = numpy.array([[2,4,5],[1,2,3],[9,8,7],[3,6,9]])

In [19]:
list_a = [[2,4,5],[1,2,3],[9,8,7],[3,6,9]]
mat_a = numpy.array(list_a)
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [20]:
import numpy as np

In [21]:
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b = np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

## Quiz2

1. Slice ค่าลบออกมาจาก mat_b 
2. Slice ```[1,2,3]``` จาก ```mat_a```
3. Slice ```[1,3],[9,7],[3,9]``` ออกมาจาก ```mat_b```  

In [22]:
mat_b[:4,:2]

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

In [23]:
mat_a[1]

array([1, 2, 3])

In [24]:
mat_b[-3:,2::2]

array([[1, 3],
       [9, 7],
       [3, 9]])

# Function ```Print```

In [1]:
print()

In [35]:
print('สวัสดี')

สวัสดี


In [36]:
print('hello')
print('สวัสดี')

hello
สวัสดี


In [41]:
print('hello',end=' ')
print('สวัสดี')

hello สวัสดี


In [38]:
print('hello','สวัสดี')

hello สวัสดี


In [39]:
print('hello','สวัสดี',sep='\n')

hello
สวัสดี


In [40]:
print('hello',end='')
print('สวัสดี')

helloสวัสดี


## HW1

เขียน function
แสดงความต่างของเวลา (Quiz1)
โดย input อยู่ในรูปแบบ ```'09:11:50 - 12:30:15'```

และทดลองรัน

* '09:11:50 - 12:30:15'
* '13:41:07 - 20:00:18'
* '00:00:00 - 23:59:59'

In [32]:
def time_1(n1,n2,n3,N1,N2,N3):
    N = ((N1*3600) + (N2*60) + N3) - ((n1*3600) + (n2*60) + n3)
    return N

print(f'ความต่างของเวลา 09:11:50 - 12:30:15 คือ {time_1(9,11,50,12,30,15)} วินาที')

ความต่างของเวลา 09:11:50 - 12:30:15 คือ 11905 วินาที


In [33]:
def time_2(e1,e2,e3,E1,E2,E3):
    E = ((E1*3600) + (E2*60) + E3) - ((e1*3600) + (e2*60) + e3)
    return E

print(f'ความต่างของเวลา 13:41:07 - 20:00:18 คือ {time_1(13,41,7,20,0,18)} วินาที')

ความต่างของเวลา 13:41:07 - 20:00:18 คือ 22751 วินาที


In [34]:
def time_3(w1,w2,w3,W1,W2,W3):
    W = ((W*3600) + (W2*60) + W3) - ((w1*3600) + (w2*60) + w3)
    return W

print(f'ความต่างของเวลา 00:00:00 - 23:59:59 คือ {time_1(0,0,0,23,59,59)} วินาที')

ความต่างของเวลา 00:00:00 - 23:59:59 คือ 86399 วินาที
